export const TEST_IDS = {
  CLEAR_ALL_FILTERS: "clear-all-filters",
  ENTITY_SUMMARY: "entity-summary",
  EXPORT_BUTTON: "export-button",
  EXPORT_SUMMARY: "export-summary",
  FILTERS: "filters",
  FILTER_CONTROLS: "filter-controls",
  FILTER_COUNT: "filter-count",
  FILTER_ITEM: "filter-item",
  FILTER_POPOVER: "filter-popover",
  FILTER_RANGE: "filter-range",
  FILTER_TERM: "filter-term",
  SEARCH_ALL_FILTERS: "search-all-filters",
  SIDEBAR: "sidebar",
  SIDEBAR_DRAWER: "sidebar-drawer",
  TABLE_FIRST_CELL: "table-first-cell",
  TABLE_PAGINATION: "table-pagination",
  TABLE_PAGINATION_PAGE: "table-pagination-page",
  TABLE_PAGINATION_RESULTS: "table-pagination-results",
  VIEW_TOGGLE: "view-toggle",
};
