import { FILE_MANIFEST_TYPE } from "../../hooks/useFileManifest/common/entities";

export const ENTITIES_FILE_MANIFEST_TYPES: FILE_MANIFEST_TYPE[] = [
  FILE_MANIFEST_TYPE.BULK_DOWNLOAD,
  FILE_MANIFEST_TYPE.DOWNLOAD_MANIFEST,
  FILE_MANIFEST_TYPE.EXPORT_TO_TERRA,
];
